/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stravalib
// SportType : An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
type SportType string

// List of SportType
const (
	ALPINE_SKI SportType = "AlpineSki"
	BACKCOUNTRY_SKI SportType = "BackcountrySki"
	BADMINTON SportType = "Badminton"
	CANOEING SportType = "Canoeing"
	CROSSFIT SportType = "Crossfit"
	E_BIKE_RIDE SportType = "EBikeRide"
	ELLIPTICAL SportType = "Elliptical"
	E_MOUNTAIN_BIKE_RIDE SportType = "EMountainBikeRide"
	GOLF SportType = "Golf"
	GRAVEL_RIDE SportType = "GravelRide"
	HANDCYCLE SportType = "Handcycle"
	HIGH_INTENSITY_INTERVAL_TRAINING SportType = "HighIntensityIntervalTraining"
	HIKE SportType = "Hike"
	ICE_SKATE SportType = "IceSkate"
	INLINE_SKATE SportType = "InlineSkate"
	KAYAKING SportType = "Kayaking"
	KITESURF SportType = "Kitesurf"
	MOUNTAIN_BIKE_RIDE SportType = "MountainBikeRide"
	NORDIC_SKI SportType = "NordicSki"
	PICKLEBALL SportType = "Pickleball"
	PILATES SportType = "Pilates"
	RACQUETBALL SportType = "Racquetball"
	RIDE SportType = "Ride"
	ROCK_CLIMBING SportType = "RockClimbing"
	ROLLER_SKI SportType = "RollerSki"
	ROWING SportType = "Rowing"
	RUN SportType = "Run"
	SAIL SportType = "Sail"
	SKATEBOARD SportType = "Skateboard"
	SNOWBOARD SportType = "Snowboard"
	SNOWSHOE SportType = "Snowshoe"
	SOCCER SportType = "Soccer"
	SQUASH SportType = "Squash"
	STAIR_STEPPER SportType = "StairStepper"
	STAND_UP_PADDLING SportType = "StandUpPaddling"
	SURFING SportType = "Surfing"
	SWIM SportType = "Swim"
	TABLE_TENNIS SportType = "TableTennis"
	TENNIS SportType = "Tennis"
	TRAIL_RUN SportType = "TrailRun"
	VELOMOBILE SportType = "Velomobile"
	VIRTUAL_RIDE SportType = "VirtualRide"
	VIRTUAL_ROW SportType = "VirtualRow"
	VIRTUAL_RUN SportType = "VirtualRun"
	WALK SportType = "Walk"
	WEIGHT_TRAINING SportType = "WeightTraining"
	WHEELCHAIR SportType = "Wheelchair"
	WINDSURF SportType = "Windsurf"
	WORKOUT SportType = "Workout"
	YOGA SportType = "Yoga"
)
