-- Code generated by 'make coderd/database/generate'. DO NOT EDIT.

CREATE TABLE athlete_efforts (
    id uuid NOT NULL,
    athlete_id integer NOT NULL,
    segment_id integer NOT NULL,
    last_checked timestamp without time zone NOT NULL,
    best_effort_id integer NOT NULL,
    kom_rank integer NOT NULL
);

CREATE TABLE athletes (
    id integer NOT NULL
);

CREATE TABLE segments (
    id integer NOT NULL,
    name text NOT NULL
);

ALTER TABLE ONLY athlete_efforts
    ADD CONSTRAINT athlete_efforts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY athletes
    ADD CONSTRAINT athletes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY segments
    ADD CONSTRAINT segments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY athlete_efforts
    ADD CONSTRAINT athlete_efforts_athlete_id_fkey FOREIGN KEY (athlete_id) REFERENCES athletes(id);

ALTER TABLE ONLY athlete_efforts
    ADD CONSTRAINT athlete_efforts_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES segments(id);

