// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Athlete struct {
	ID   int32         `db:"id" json:"id"`
	Test sql.NullInt32 `db:"test" json:"test"`
}

type AthleteEffort struct {
	ID           uuid.UUID `db:"id" json:"id"`
	AthleteID    int32     `db:"athlete_id" json:"athlete_id"`
	SegmentID    int32     `db:"segment_id" json:"segment_id"`
	LastChecked  time.Time `db:"last_checked" json:"last_checked"`
	BestEffortID int32     `db:"best_effort_id" json:"best_effort_id"`
	KomRank      int32     `db:"kom_rank" json:"kom_rank"`
}

type Segment struct {
	ID   int32  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}
