// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

const deleteActivity = `-- name: DeleteActivity :one
DELETE FROM
	activity_summary
WHERE
	id = $1
RETURNING id, athlete_id, upload_id, external_id, name, distance, moving_time, elapsed_time, total_elevation_gain, activity_type, sport_type, workout_type, start_date, start_date_local, timezone, utc_offset, achievement_count, kudos_count, comment_count, athlete_count, photo_count, map_id, trainer, commute, manual, private, flagged, gear_id, average_speed, max_speed, device_watts, has_heartrate, pr_count, total_photo_count, calories, updated_at
`

func (q *sqlQuerier) DeleteActivity(ctx context.Context, id int64) (ActivitySummary, error) {
	row := q.db.QueryRowContext(ctx, deleteActivity, id)
	var i ActivitySummary
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.UploadID,
		&i.ExternalID,
		&i.Name,
		&i.Distance,
		&i.MovingTime,
		&i.ElapsedTime,
		&i.TotalElevationGain,
		&i.ActivityType,
		&i.SportType,
		&i.WorkoutType,
		&i.StartDate,
		&i.StartDateLocal,
		&i.Timezone,
		&i.UtcOffset,
		&i.AchievementCount,
		&i.KudosCount,
		&i.CommentCount,
		&i.AthleteCount,
		&i.PhotoCount,
		&i.MapID,
		&i.Trainer,
		&i.Commute,
		&i.Manual,
		&i.Private,
		&i.Flagged,
		&i.GearID,
		&i.AverageSpeed,
		&i.MaxSpeed,
		&i.DeviceWatts,
		&i.HasHeartrate,
		&i.PrCount,
		&i.TotalPhotoCount,
		&i.Calories,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivitySummary = `-- name: GetActivitySummary :one
SELECT
	id, athlete_id, upload_id, external_id, name, distance, moving_time, elapsed_time, total_elevation_gain, activity_type, sport_type, workout_type, start_date, start_date_local, timezone, utc_offset, achievement_count, kudos_count, comment_count, athlete_count, photo_count, map_id, trainer, commute, manual, private, flagged, gear_id, average_speed, max_speed, device_watts, has_heartrate, pr_count, total_photo_count, calories, updated_at
FROM
    activity_summary
WHERE
    id = $1
`

func (q *sqlQuerier) GetActivitySummary(ctx context.Context, id int64) (ActivitySummary, error) {
	row := q.db.QueryRowContext(ctx, getActivitySummary, id)
	var i ActivitySummary
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.UploadID,
		&i.ExternalID,
		&i.Name,
		&i.Distance,
		&i.MovingTime,
		&i.ElapsedTime,
		&i.TotalElevationGain,
		&i.ActivityType,
		&i.SportType,
		&i.WorkoutType,
		&i.StartDate,
		&i.StartDateLocal,
		&i.Timezone,
		&i.UtcOffset,
		&i.AchievementCount,
		&i.KudosCount,
		&i.CommentCount,
		&i.AthleteCount,
		&i.PhotoCount,
		&i.MapID,
		&i.Trainer,
		&i.Commute,
		&i.Manual,
		&i.Private,
		&i.Flagged,
		&i.GearID,
		&i.AverageSpeed,
		&i.MaxSpeed,
		&i.DeviceWatts,
		&i.HasHeartrate,
		&i.PrCount,
		&i.TotalPhotoCount,
		&i.Calories,
		&i.UpdatedAt,
	)
	return i, err
}

const updateActivityName = `-- name: UpdateActivityName :exec
UPDATE activity_summary
SET
    name = $2
WHERE
    id = $1
`

type UpdateActivityNameParams struct {
	ID   int64  `db:"id" json:"id"`
	Name string `db:"name" json:"name"`
}

func (q *sqlQuerier) UpdateActivityName(ctx context.Context, arg UpdateActivityNameParams) error {
	_, err := q.db.ExecContext(ctx, updateActivityName, arg.ID, arg.Name)
	return err
}

const upsertActivityDetail = `-- name: UpsertActivityDetail :one
INSERT INTO
	activity_detail(
		updated_at, id, athlete_id, start_latlng,
		end_latlng, from_accepted_tag, average_cadence, average_temp,
		average_watts, weighted_average_watts, kilojoules, max_watts,
	    elev_high, elev_low, suffer_score, embed_token,
	    segment_leaderboard_opt_out, leaderboard_opt_out, num_segment_efforts,
	    premium_fetch, updated_at, map_id
)
VALUES
	(Now(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17,
	 $18, $19, $20, $21)
ON CONFLICT
	(id)
	DO UPDATE SET
	updated_at = Now(),
	athlete_id = $2,
	start_latlng = $3,
	end_latlng = $4,
	from_accepted_tag = $5,
	average_cadence = $6,
	average_temp = $7,
	average_watts = $8,
	weighted_average_watts = $9,
	kilojoules = $10,
	max_watts = $11,
	elev_high = $12,
	elev_low = $13,
	suffer_score = $14,
	embed_token = $15,
	segment_leaderboard_opt_out = $16,
	leaderboard_opt_out = $17,
	num_segment_efforts = $18,
	premium_fetch = $19,
	updated_at = $20,
	map_id = $21
RETURNING id, athlete_id, start_latlng, end_latlng, from_accepted_tag, average_cadence, average_temp, average_watts, weighted_average_watts, kilojoules, max_watts, elev_high, elev_low, suffer_score, embed_token, segment_leaderboard_opt_out, leaderboard_opt_out, num_segment_efforts, premium_fetch, updated_at, map_id
`

type UpsertActivityDetailParams struct {
	ID                       int64     `db:"id" json:"id"`
	AthleteID                int64     `db:"athlete_id" json:"athlete_id"`
	StartLatlng              []float64 `db:"start_latlng" json:"start_latlng"`
	EndLatlng                []float64 `db:"end_latlng" json:"end_latlng"`
	FromAcceptedTag          bool      `db:"from_accepted_tag" json:"from_accepted_tag"`
	AverageCadence           float64   `db:"average_cadence" json:"average_cadence"`
	AverageTemp              float64   `db:"average_temp" json:"average_temp"`
	AverageWatts             float64   `db:"average_watts" json:"average_watts"`
	WeightedAverageWatts     float64   `db:"weighted_average_watts" json:"weighted_average_watts"`
	Kilojoules               float64   `db:"kilojoules" json:"kilojoules"`
	MaxWatts                 float64   `db:"max_watts" json:"max_watts"`
	ElevHigh                 float64   `db:"elev_high" json:"elev_high"`
	ElevLow                  float64   `db:"elev_low" json:"elev_low"`
	SufferScore              int32     `db:"suffer_score" json:"suffer_score"`
	EmbedToken               string    `db:"embed_token" json:"embed_token"`
	SegmentLeaderboardOptOut bool      `db:"segment_leaderboard_opt_out" json:"segment_leaderboard_opt_out"`
	LeaderboardOptOut        bool      `db:"leaderboard_opt_out" json:"leaderboard_opt_out"`
	NumSegmentEfforts        int32     `db:"num_segment_efforts" json:"num_segment_efforts"`
	PremiumFetch             bool      `db:"premium_fetch" json:"premium_fetch"`
	UpdatedAt                time.Time `db:"updated_at" json:"updated_at"`
	MapID                    string    `db:"map_id" json:"map_id"`
}

func (q *sqlQuerier) UpsertActivityDetail(ctx context.Context, arg UpsertActivityDetailParams) (ActivityDetail, error) {
	row := q.db.QueryRowContext(ctx, upsertActivityDetail,
		arg.ID,
		arg.AthleteID,
		pq.Array(arg.StartLatlng),
		pq.Array(arg.EndLatlng),
		arg.FromAcceptedTag,
		arg.AverageCadence,
		arg.AverageTemp,
		arg.AverageWatts,
		arg.WeightedAverageWatts,
		arg.Kilojoules,
		arg.MaxWatts,
		arg.ElevHigh,
		arg.ElevLow,
		arg.SufferScore,
		arg.EmbedToken,
		arg.SegmentLeaderboardOptOut,
		arg.LeaderboardOptOut,
		arg.NumSegmentEfforts,
		arg.PremiumFetch,
		arg.UpdatedAt,
		arg.MapID,
	)
	var i ActivityDetail
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		pq.Array(&i.StartLatlng),
		pq.Array(&i.EndLatlng),
		&i.FromAcceptedTag,
		&i.AverageCadence,
		&i.AverageTemp,
		&i.AverageWatts,
		&i.WeightedAverageWatts,
		&i.Kilojoules,
		&i.MaxWatts,
		&i.ElevHigh,
		&i.ElevLow,
		&i.SufferScore,
		&i.EmbedToken,
		&i.SegmentLeaderboardOptOut,
		&i.LeaderboardOptOut,
		&i.NumSegmentEfforts,
		&i.PremiumFetch,
		&i.UpdatedAt,
		&i.MapID,
	)
	return i, err
}

const upsertActivitySummary = `-- name: UpsertActivitySummary :one
INSERT INTO
	activity_summary(
		updated_at, id, athlete_id, upload_id, external_id, name,
	    distance, moving_time, elapsed_time, total_elevation_gain,
	    activity_type, sport_type, workout_type, start_date,
	    start_date_local, timezone, utc_offset, achievement_count,
	    kudos_count, comment_count, athlete_count, photo_count, map_id,
	    trainer, commute, manual, private, flagged, gear_id, average_speed,
	    max_speed, device_watts, has_heartrate, pr_count, total_photo_count,
	    calories
)
VALUES
	(Now(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
	 $21, $22, $23, $24, $25, $26, $27, $28, $29, $30, $31, $32, $33, $34, $35)
ON CONFLICT
	(id)
	DO UPDATE SET
		updated_at = Now(),
		athlete_id = $2,
		upload_id = $3,
		external_id = $4,
		name = $5,
		distance = $6,
		moving_time = $7,
		elapsed_time = $8,
		total_elevation_gain = $9,
		activity_type = $10,
		sport_type = $11,
		workout_type = $12,
		start_date = $13,
		start_date_local = $14,
		timezone = $15,
		utc_offset = $16,
		achievement_count = $17,
		kudos_count = $18,
		comment_count = $19,
		athlete_count = $20,
		photo_count = $21,
		map_id = $22,
		trainer = $23,
		commute = $24,
		manual = $25,
		private = $26,
		flagged = $27,
		gear_id = $28,
		average_speed = $29,
		max_speed = $30,
		device_watts = $31,
		has_heartrate = $32,
		pr_count = $33,
		total_photo_count = $34,
		calories = $35
RETURNING id, athlete_id, upload_id, external_id, name, distance, moving_time, elapsed_time, total_elevation_gain, activity_type, sport_type, workout_type, start_date, start_date_local, timezone, utc_offset, achievement_count, kudos_count, comment_count, athlete_count, photo_count, map_id, trainer, commute, manual, private, flagged, gear_id, average_speed, max_speed, device_watts, has_heartrate, pr_count, total_photo_count, calories, updated_at
`

type UpsertActivitySummaryParams struct {
	ID                 int64     `db:"id" json:"id"`
	AthleteID          int64     `db:"athlete_id" json:"athlete_id"`
	UploadID           int64     `db:"upload_id" json:"upload_id"`
	ExternalID         string    `db:"external_id" json:"external_id"`
	Name               string    `db:"name" json:"name"`
	Distance           float64   `db:"distance" json:"distance"`
	MovingTime         float64   `db:"moving_time" json:"moving_time"`
	ElapsedTime        float64   `db:"elapsed_time" json:"elapsed_time"`
	TotalElevationGain float64   `db:"total_elevation_gain" json:"total_elevation_gain"`
	ActivityType       string    `db:"activity_type" json:"activity_type"`
	SportType          string    `db:"sport_type" json:"sport_type"`
	WorkoutType        int32     `db:"workout_type" json:"workout_type"`
	StartDate          time.Time `db:"start_date" json:"start_date"`
	StartDateLocal     time.Time `db:"start_date_local" json:"start_date_local"`
	Timezone           string    `db:"timezone" json:"timezone"`
	UtcOffset          float64   `db:"utc_offset" json:"utc_offset"`
	AchievementCount   int32     `db:"achievement_count" json:"achievement_count"`
	KudosCount         int32     `db:"kudos_count" json:"kudos_count"`
	CommentCount       int32     `db:"comment_count" json:"comment_count"`
	AthleteCount       int32     `db:"athlete_count" json:"athlete_count"`
	PhotoCount         int32     `db:"photo_count" json:"photo_count"`
	MapID              string    `db:"map_id" json:"map_id"`
	Trainer            bool      `db:"trainer" json:"trainer"`
	Commute            bool      `db:"commute" json:"commute"`
	Manual             bool      `db:"manual" json:"manual"`
	Private            bool      `db:"private" json:"private"`
	Flagged            bool      `db:"flagged" json:"flagged"`
	GearID             string    `db:"gear_id" json:"gear_id"`
	AverageSpeed       float64   `db:"average_speed" json:"average_speed"`
	MaxSpeed           float64   `db:"max_speed" json:"max_speed"`
	DeviceWatts        bool      `db:"device_watts" json:"device_watts"`
	HasHeartrate       bool      `db:"has_heartrate" json:"has_heartrate"`
	PrCount            int32     `db:"pr_count" json:"pr_count"`
	TotalPhotoCount    int32     `db:"total_photo_count" json:"total_photo_count"`
	Calories           float64   `db:"calories" json:"calories"`
}

func (q *sqlQuerier) UpsertActivitySummary(ctx context.Context, arg UpsertActivitySummaryParams) (ActivitySummary, error) {
	row := q.db.QueryRowContext(ctx, upsertActivitySummary,
		arg.ID,
		arg.AthleteID,
		arg.UploadID,
		arg.ExternalID,
		arg.Name,
		arg.Distance,
		arg.MovingTime,
		arg.ElapsedTime,
		arg.TotalElevationGain,
		arg.ActivityType,
		arg.SportType,
		arg.WorkoutType,
		arg.StartDate,
		arg.StartDateLocal,
		arg.Timezone,
		arg.UtcOffset,
		arg.AchievementCount,
		arg.KudosCount,
		arg.CommentCount,
		arg.AthleteCount,
		arg.PhotoCount,
		arg.MapID,
		arg.Trainer,
		arg.Commute,
		arg.Manual,
		arg.Private,
		arg.Flagged,
		arg.GearID,
		arg.AverageSpeed,
		arg.MaxSpeed,
		arg.DeviceWatts,
		arg.HasHeartrate,
		arg.PrCount,
		arg.TotalPhotoCount,
		arg.Calories,
	)
	var i ActivitySummary
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.UploadID,
		&i.ExternalID,
		&i.Name,
		&i.Distance,
		&i.MovingTime,
		&i.ElapsedTime,
		&i.TotalElevationGain,
		&i.ActivityType,
		&i.SportType,
		&i.WorkoutType,
		&i.StartDate,
		&i.StartDateLocal,
		&i.Timezone,
		&i.UtcOffset,
		&i.AchievementCount,
		&i.KudosCount,
		&i.CommentCount,
		&i.AthleteCount,
		&i.PhotoCount,
		&i.MapID,
		&i.Trainer,
		&i.Commute,
		&i.Manual,
		&i.Private,
		&i.Flagged,
		&i.GearID,
		&i.AverageSpeed,
		&i.MaxSpeed,
		&i.DeviceWatts,
		&i.HasHeartrate,
		&i.PrCount,
		&i.TotalPhotoCount,
		&i.Calories,
		&i.UpdatedAt,
	)
	return i, err
}

const getAthleteLogin = `-- name: GetAthleteLogin :one
SELECT athlete_id, summit, provider_id, created_at, updated_at, oauth_access_token, oauth_refresh_token, oauth_expiry, oauth_token_type, id FROM athlete_logins WHERE athlete_id = $1
`

func (q *sqlQuerier) GetAthleteLogin(ctx context.Context, athleteID int64) (AthleteLogin, error) {
	row := q.db.QueryRowContext(ctx, getAthleteLogin, athleteID)
	var i AthleteLogin
	err := row.Scan(
		&i.AthleteID,
		&i.Summit,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthExpiry,
		&i.OauthTokenType,
		&i.ID,
	)
	return i, err
}

const upsertAthlete = `-- name: UpsertAthlete :one
INSERT INTO
	athletes(
	fetched_at, id, created_at, updated_at,
		summit, username, firstname, lastname, sex, city, state, country,
		follow_count, friend_count, measurement_preference, ftp, weight, clubs
)
VALUES
	(Now(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT
	(id)
	DO UPDATE SET
		fetched_at = Now(),
		created_at = $2,
		updated_at = $3,
		summit = $4,
		username = $5,
		firstname = $6,
		lastname = $7,
		sex = $8,
		city = $9,
		state = $10,
		country = $11,
		follow_count = $12,
		friend_count = $13,
		measurement_preference = $14,
		ftp = $15,
		weight = $16,
		clubs = $17
RETURNING id, summit, username, firstname, lastname, sex, city, state, country, follow_count, friend_count, measurement_preference, ftp, weight, clubs, created_at, updated_at, fetched_at
`

type UpsertAthleteParams struct {
	ID                    int64           `db:"id" json:"id"`
	CreatedAt             time.Time       `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time       `db:"updated_at" json:"updated_at"`
	Summit                bool            `db:"summit" json:"summit"`
	Username              string          `db:"username" json:"username"`
	Firstname             string          `db:"firstname" json:"firstname"`
	Lastname              string          `db:"lastname" json:"lastname"`
	Sex                   string          `db:"sex" json:"sex"`
	City                  string          `db:"city" json:"city"`
	State                 string          `db:"state" json:"state"`
	Country               string          `db:"country" json:"country"`
	FollowCount           int32           `db:"follow_count" json:"follow_count"`
	FriendCount           int32           `db:"friend_count" json:"friend_count"`
	MeasurementPreference string          `db:"measurement_preference" json:"measurement_preference"`
	Ftp                   float64         `db:"ftp" json:"ftp"`
	Weight                float64         `db:"weight" json:"weight"`
	Clubs                 json.RawMessage `db:"clubs" json:"clubs"`
}

func (q *sqlQuerier) UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) (Athlete, error) {
	row := q.db.QueryRowContext(ctx, upsertAthlete,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Summit,
		arg.Username,
		arg.Firstname,
		arg.Lastname,
		arg.Sex,
		arg.City,
		arg.State,
		arg.Country,
		arg.FollowCount,
		arg.FriendCount,
		arg.MeasurementPreference,
		arg.Ftp,
		arg.Weight,
		arg.Clubs,
	)
	var i Athlete
	err := row.Scan(
		&i.ID,
		&i.Summit,
		&i.Username,
		&i.Firstname,
		&i.Lastname,
		&i.Sex,
		&i.City,
		&i.State,
		&i.Country,
		&i.FollowCount,
		&i.FriendCount,
		&i.MeasurementPreference,
		&i.Ftp,
		&i.Weight,
		&i.Clubs,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FetchedAt,
	)
	return i, err
}

const upsertAthleteLogin = `-- name: UpsertAthleteLogin :one
INSERT INTO
	athlete_logins(
		created_at, updated_at, id,
             athlete_id, summit, provider_id, oauth_access_token,
             oauth_refresh_token, oauth_expiry, oauth_token_type
	)
VALUES
    (Now(), Now(), gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT
	(athlete_id)
DO UPDATE SET
	updated_at = Now(),
	summit = $2,
	provider_id = $3,
	oauth_access_token = $4,
	oauth_refresh_token = $5,
	oauth_expiry = $6,
	oauth_token_type = $7
RETURNING athlete_id, summit, provider_id, created_at, updated_at, oauth_access_token, oauth_refresh_token, oauth_expiry, oauth_token_type, id
`

type UpsertAthleteLoginParams struct {
	AthleteID         int64     `db:"athlete_id" json:"athlete_id"`
	Summit            bool      `db:"summit" json:"summit"`
	ProviderID        string    `db:"provider_id" json:"provider_id"`
	OauthAccessToken  string    `db:"oauth_access_token" json:"oauth_access_token"`
	OauthRefreshToken string    `db:"oauth_refresh_token" json:"oauth_refresh_token"`
	OauthExpiry       time.Time `db:"oauth_expiry" json:"oauth_expiry"`
	OauthTokenType    string    `db:"oauth_token_type" json:"oauth_token_type"`
}

func (q *sqlQuerier) UpsertAthleteLogin(ctx context.Context, arg UpsertAthleteLoginParams) (AthleteLogin, error) {
	row := q.db.QueryRowContext(ctx, upsertAthleteLogin,
		arg.AthleteID,
		arg.Summit,
		arg.ProviderID,
		arg.OauthAccessToken,
		arg.OauthRefreshToken,
		arg.OauthExpiry,
		arg.OauthTokenType,
	)
	var i AthleteLogin
	err := row.Scan(
		&i.AthleteID,
		&i.Summit,
		&i.ProviderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthAccessToken,
		&i.OauthRefreshToken,
		&i.OauthExpiry,
		&i.OauthTokenType,
		&i.ID,
	)
	return i, err
}

const upsertMap = `-- name: UpsertMap :one
INSERT INTO
	maps(
	updated_at, id, polyline, summary_polyline
)
VALUES
	(Now(), $1, $2, $3)
ON CONFLICT
	(id)
	DO UPDATE SET
		updated_at = Now(),
		polyline = $2,
		summary_polyline = $3
RETURNING id, polyline, summary_polyline, updated_at
`

type UpsertMapParams struct {
	ID              string `db:"id" json:"id"`
	Polyline        string `db:"polyline" json:"polyline"`
	SummaryPolyline string `db:"summary_polyline" json:"summary_polyline"`
}

func (q *sqlQuerier) UpsertMap(ctx context.Context, arg UpsertMapParams) (Map, error) {
	row := q.db.QueryRowContext(ctx, upsertMap, arg.ID, arg.Polyline, arg.SummaryPolyline)
	var i Map
	err := row.Scan(
		&i.ID,
		&i.Polyline,
		&i.SummaryPolyline,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSegmentEffort = `-- name: UpsertSegmentEffort :one
INSERT INTO
	segment_efforts(
		updated_at,
		id, athlete_id, segment_id, name, elapsed_time,
		moving_time, start_date, start_date_local, distance,
		start_index, end_index, device_watts, average_watts,
		kom_rank, pr_rank, activities_id
	)
VALUES
	(Now(), $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT
	(id)
	DO UPDATE SET
		updated_at = Now(),
		athlete_id = $2,
		segment_id = $3,
		name = $4,
		elapsed_time = $5,
		moving_time = $6,
		start_date = $7,
		start_date_local = $8,
		distance = $9,
		start_index = $10,
		end_index = $11,
		device_watts = $12,
		average_watts = $13,
		kom_rank = $14,
		pr_rank = $15,
		activities_id = $16
	RETURNING id, athlete_id, segment_id, name, elapsed_time, moving_time, start_date, start_date_local, distance, start_index, end_index, device_watts, average_watts, kom_rank, pr_rank, updated_at, activities_id
`

type UpsertSegmentEffortParams struct {
	ID             int64         `db:"id" json:"id"`
	AthleteID      int64         `db:"athlete_id" json:"athlete_id"`
	SegmentID      int64         `db:"segment_id" json:"segment_id"`
	Name           string        `db:"name" json:"name"`
	ElapsedTime    float64       `db:"elapsed_time" json:"elapsed_time"`
	MovingTime     float64       `db:"moving_time" json:"moving_time"`
	StartDate      time.Time     `db:"start_date" json:"start_date"`
	StartDateLocal time.Time     `db:"start_date_local" json:"start_date_local"`
	Distance       float64       `db:"distance" json:"distance"`
	StartIndex     int32         `db:"start_index" json:"start_index"`
	EndIndex       int32         `db:"end_index" json:"end_index"`
	DeviceWatts    bool          `db:"device_watts" json:"device_watts"`
	AverageWatts   float64       `db:"average_watts" json:"average_watts"`
	KomRank        sql.NullInt32 `db:"kom_rank" json:"kom_rank"`
	PrRank         sql.NullInt32 `db:"pr_rank" json:"pr_rank"`
	ActivitiesID   int64         `db:"activities_id" json:"activities_id"`
}

func (q *sqlQuerier) UpsertSegmentEffort(ctx context.Context, arg UpsertSegmentEffortParams) (SegmentEffort, error) {
	row := q.db.QueryRowContext(ctx, upsertSegmentEffort,
		arg.ID,
		arg.AthleteID,
		arg.SegmentID,
		arg.Name,
		arg.ElapsedTime,
		arg.MovingTime,
		arg.StartDate,
		arg.StartDateLocal,
		arg.Distance,
		arg.StartIndex,
		arg.EndIndex,
		arg.DeviceWatts,
		arg.AverageWatts,
		arg.KomRank,
		arg.PrRank,
		arg.ActivitiesID,
	)
	var i SegmentEffort
	err := row.Scan(
		&i.ID,
		&i.AthleteID,
		&i.SegmentID,
		&i.Name,
		&i.ElapsedTime,
		&i.MovingTime,
		&i.StartDate,
		&i.StartDateLocal,
		&i.Distance,
		&i.StartIndex,
		&i.EndIndex,
		&i.DeviceWatts,
		&i.AverageWatts,
		&i.KomRank,
		&i.PrRank,
		&i.UpdatedAt,
		&i.ActivitiesID,
	)
	return i, err
}

const insertWebhookDump = `-- name: InsertWebhookDump :one
INSERT INTO
	webhook_dump(
	id, recorded_at, raw
)
VALUES
	(gen_random_uuid(), Now(), $1)
RETURNING id, recorded_at, raw
`

func (q *sqlQuerier) InsertWebhookDump(ctx context.Context, rawJson string) (WebhookDump, error) {
	row := q.db.QueryRowContext(ctx, insertWebhookDump, rawJson)
	var i WebhookDump
	err := row.Scan(&i.ID, &i.RecordedAt, &i.Raw)
	return i, err
}
