// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package database

import (
	"context"
)

type sqlcQuerier interface {
	GetAthletes(ctx context.Context) ([]Athlete, error)
	InsertWebhookDump(ctx context.Context, rawJson string) error
	UpsertAthlete(ctx context.Context, arg UpsertAthleteParams) (Athlete, error)
}

var _ sqlcQuerier = (*sqlQuerier)(nil)
